@echo off
:: ============================================================
:: UFCL Mobile — Patch android/app/build.gradle with signing config
:: Run this ONCE after 02_prebuild.bat has generated android/
:: It injects the keystore signing block into Gradle automatically.
:: ============================================================

setlocal

cd /d "%~dp0.."

if not exist android\app\build.gradle (
    echo ERROR: android\app\build.gradle not found. Run 02_prebuild.bat first.
    pause
    exit /b 1
)

echo.
echo ============================================================
echo  Patching android/app/build.gradle with signing config
echo ============================================================
echo.

:: Write the Gradle signing config as a separate include file
(
echo // Auto-generated by 06_configure_signing.bat — do not edit manually.
echo // Loads signing config from keystore.properties at build time.
echo android {
echo     signingConfigs {
echo         release {
echo             def props = new Properties^(^)
echo             def propsFile = rootProject.file^('../../release/keystore.properties'^)
echo             if ^(propsFile.exists^(^)^) { props.load^(new FileInputStream^(propsFile^)^) }
echo             storeFile     file^(props['KEYSTORE_FILE'] ?: '''^)
echo             storePassword props['KEYSTORE_PASSWORD'] ?: ''
echo             keyAlias      props['KEY_ALIAS'] ?: ''
echo             keyPassword   props['KEY_PASSWORD'] ?: ''
echo         }
echo     }
echo     buildTypes {
echo         release {
echo             signingConfig signingConfigs.release
echo             minifyEnabled false
echo         }
echo     }
echo }
) > android\app\signing.gradle

:: Check if signing.gradle is already applied in build.gradle
findstr /c:"signing.gradle" android\app\build.gradle >nul
if %ERRORLEVEL% EQU 0 (
    echo signing.gradle already applied in build.gradle — skipping.
) else (
    echo apply from: 'signing.gradle'>> android\app\build.gradle
    echo.
    echo Appended signing config to android\app\build.gradle
)

echo.
echo ============================================================
echo  Signing config applied.
echo ============================================================
echo.
echo Now copy release\keystore.properties.template to
echo release\keystore.properties and fill in your passwords.
echo Then run 04_build_release_apk.bat to build.
echo.
pause
