const dotenv = require('dotenv');
const { pool } = require('./pool');

dotenv.config();

async function clearData() {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    // Null out FK from app_users → warehouses so we can drop the constraint
    await client.query('UPDATE app_users SET workshop_id = NULL');

    // Find and drop the FK constraint (name is auto-generated by pg)
    const { rows } = await client.query(`
      SELECT conname FROM pg_constraint
      WHERE conrelid = 'app_users'::regclass
        AND contype = 'f'
        AND conname ILIKE '%workshop%'
    `);
    if (rows.length) {
      await client.query(`ALTER TABLE app_users DROP CONSTRAINT "${rows[0].conname}"`);
    }

    // Truncate all tables except app_users (CASCADE handles FK order automatically)
    await client.query(`
      TRUNCATE
        wk_transfer_items,
        wk_transfers,
        wk_consumption,
        wk_stock,
        wk_items,
        machine_fuel_logs,
        casuals,
        casual_labour_requests,
        value_added_timber,
        log_transport,
        compartments,
        machine_maintenance_schedules,
        machine_log_categories,
        machine_daily_logs,
        machine_kpi_targets,
        machine_kpi_definitions,
        machines,
        machine_categories,
        pending_edits,
        transport_jobs,
        transport_companies,
        harvest_logs,
        dispatch_requests,
        delivery_orders,
        maintenance_records,
        fuel_logs,
        vehicles,
        stock_movements,
        stock_levels,
        stock_catalog,
        warehouses,
        kpi_budgets,
        weekly_performance_comments,
        product_catalog,
        weekly_expenses,
        expense_categories,
        monthly_approvals,
        change_requests,
        logistics_items,
        sales_orders,
        customers,
        daily_logs,
        products,
        material_requests,
        deletion_requests,
        stock_categories,
        notifications_read,
        notifications,
        audit_log,
        role_definitions
      RESTART IDENTITY CASCADE
    `);

    // Restore the FK constraint (workshop_id is now NULL for all users so it will validate)
    await client.query(`
      ALTER TABLE app_users
        ADD CONSTRAINT app_users_workshop_id_fkey
        FOREIGN KEY (workshop_id) REFERENCES warehouses(id)
    `);

    await client.query('COMMIT');
    console.log('Done. All data cleared except app_users.');
    console.log('Run "npm run migrate" to restore reference data (roles, categories, warehouses).');
  } catch (e) {
    await client.query('ROLLBACK');
    throw e;
  } finally {
    client.release();
  }
}

clearData()
  .then(() => process.exit(0))
  .catch(e => { console.error(e); process.exit(1); })
  .finally(() => pool.end());
